[tool.poetry.dependencies]
fastapi = "^0.85.0"
uvicorn = "^0.18.3"
pydantic = "^1.10.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"
mypy = "^0.971"
black = "^22.8.0"
pylint = "^2.15.3"
httpx = "^0.23.0"
trio = "^0.21.0"
pytest-cov = "^4.0.0"
isort = "^5.10.1"